name: >
  Validate Datadog Service Metadata

description: >
  Validate the content of service.datadog.yaml

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -L -o meta.json 'http://json-schema.org/draft-07/schema#'
      working-directory: ${{ github.action_path }}

    - shell: bash
      run: |
        curl -L -O 'https://raw.githubusercontent.com/DataDog/schema/main/service-catalog/v2/schema.json'
      working-directory: ${{ github.action_path }}

    - shell: bash
      name: test debug print
      run: cat "${{ github.action_path }}/package.json"

    - id: pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: true
        version: "10.15.1"
        dest: ${{ github.action_path }}/setup-pnpm

    - shell: bash
      run: |
        ${{ steps.pnpm.outputs.bin_dest }}/pnpm install
      working-directory: ${{ github.action_path }}

    - shell: bash
      run: |
        ${{ github.action_path }}/node_modules/.bin/pajv \
          -s ${{ github.action_path }}/schema.json \
          -m ${{ github.action_path }}/meta.json \
          -d ${{ github.workspace }}/service.datadog.yaml \
          --errors=text
