name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - service.datadog.yaml
      - .github/workflows/dd-service.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            service.datadog.yaml
      - uses: "chris-martin/datadog-service-validate@dev"
